# Generated by Django 6.0.5 on 2026-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='inventory',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
