# Generated by Django 6.0.5 on 2026-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_drug_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
