# Generated by Django 6.0.5 on 2026-05-09 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_drug_cost_price'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.drug')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.sale')),
            ],
        ),
    ]
